module.exports = [
    { id: 1, name: 'what is apple to apple', authorId: 1 },
    { id: 2, name: 'Color design guideline', authorId: 2 },
    { id: 3, name: 'Don\'t talk', authorId: 1 },
    { id: 4, name: 'Tell me that', authorId: 3 },
    { id: 5, name: 'i love you', authorId: 1 },
    { id: 6, name: 'what is visual studio', authorId: 2 },
    { id: 7, name: 'why using vs code', authorId: 2 },
    { id: 8, name: 'I like windows and node.js', authorId: 2 },
    { id: 9, name: 'I love apple', authorId: 1 },
    { id: 10, name: 'C# keys', authorId: 1 },
    { id: 11, name: 'Learn node.js', authorId: 3 },
    { id: 12, name: 'why use mac', authorId: 3 },
    { id: 13, name: 'Heal the world', authorId: 4 },
];